version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_unique_id
        tests:
          - unique
          - not_null
      - name: customer_city
        tests:
          - not_null
      - name: customer_state
        tests:
          - not_null

  - name: dim_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_geolocation
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - not_null
      - name: geolocation_city
        tests:
          - not_null
      - name: geolocation_state
        tests:
          - not_null